### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Divyam53** [lakshayg/tensorflow-build-archived#13]
After installing your library for ubuntu 16.04, python 2.7, I got this error

**On compiling cnn_face.py** -

Traceback (most recent call last):
  File "cnn_face.py", line 12, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 30, in <module>
    from tensorflow.python.framework import function
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 32, in <module>
    from tensorflow.python.ops import array_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 97, in <module>
    from tensorflow.python.ops import gen_array_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 8, in <module>
    from tensorflow.python.eager import execute as _execute
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/execute.py", line 29, in <module>
    from tensorflow.python.eager import tape
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/tape.py", line 23, in <module>
    from autograd import container_types
ImportError: cannot import name container_types

**Comment by lakshayg** [comment]
Looking into it. Rebuilding the wheel takes me ~2 hours. Please check back after some time.

**Comment by lakshayg** [comment]
I have uploaded a TF1.4.0 for Py2.7 and Ubuntu 16.04. Please check if it solves your issue.

**Comment by jesseweisberg** [comment]
get the same error for installing Ubuntu 16.04- python 3.5 library

**Comment by lakshayg** [comment]
I have uploaded a new wheel. Please see if it works. @jesseweisberg

**Comment by jesseweisberg** [comment]
Fixed! Thanks @lakshayg !
